### PR TITLE
Adds support to render Regional GKE Clusters

### LINKED ISSUE #1510: GKE Renderer: Invalid value for zone: us-west1
I tried the GKE renderer. I pasted the link into a code cell

```
https://console.cloud.google.com/kubernetes/list/overview?hl=en&project=contr-jeremylewi
```

I got the error

```
Failed to get Google Cloud resource data, reason: Invalid value for field 'zone': 'us-west1'. Unknown zone.
```

`us-west1` is a region not a zone so that would nominally explain the error. I have a regional cluster in us-west1 but not a zonal cluster.

### PR DESCRIPTION
**Pull request by pastuxso**
The bug is occurring because the request to retrieve the machine type requires the zone, but we were passing the region when the cluster is actually regional.

In the case of a regional cluster, multiple zones are listed in `cluster.locations`. Therefore, it is now necessary to display the count of nodes, total CPU, and total memory requesting the machine type for each zone.

Closes #1510

### CODE REVIEW

**Comment by jlewi** [comment]
@pastuxso Thanks for the quick fix. Could you explain what the bug was and how this fixes it?

**Review by sourishkrout — APPROVED** [review]
✅ works. if you could answer @jlewi's question, please @pastuxso.

**Comment by pastuxso** [comment]
@jlewi 

> @pastuxso Thanks for the quick fix. Could you explain what the bug was and how this fixes it?

Sure, I've updated the pull request description to provide more details about the changes. Feel free to ask me if you have any questions.

**Comment by jlewi** [comment]
Great thank you.
LGTM

**Pull request merged**
