### PR TITLE
Prompt user for every cell when executing 'Run All'

### LINKED ISSUE #98: Ask for confirmation in between cells for "Run all"
Getting ahead of unintentional execution of cells as part of clicking "run all", let's consider inserting a confirmation step.

A later improvement could be automatically detecting "sensitive" cells and selectively asking for confirmation.

### PR DESCRIPTION
**Pull request by christian-bromann**
Fixes #98

runall

### CODE REVIEW

**Comment by sourishkrout** [comment]
I'd be curious to see if a modal-based notification vs quickpicker would work better here?

https://code.visualstudio.com/api/references/vscode-api#MessageOptions

**Comment by christian-bromann** [comment]
Here is the modal based notification. A bit more subtle, folks might miss it depending on the window size.

parallel2

**Comment by sourishkrout** [comment]
> Here is the modal based notification.

I thought notifs in modal mode would cover the viewport entirely. Did you set `modal: true` in the options? As per

image

**Comment by christian-bromann** [comment]
Ah, gotcha, this would look like this:

parallel3

**Comment by sourishkrout** [comment]
Thanks! Which one do you like best @christian-bromann? I'm torn between picker vs modal.

@admc any preference since you are usually opinionated about UI?

**Comment by christian-bromann** [comment]
> Thanks! Which one do you like best @christian-bromann?

My order of liking is:

- __1st__ first solution, less dominant but visible enough and easy to navigate with the arrow keys
- __2nd__ last solution, very dominant, no selection possible with arrow keys but tab keys
- __3rd__ middle solution, can be overseen by the user, mouse handling required

**Comment by admc** [comment]
- Quick picker
- Modal gets in the way of looking at the cell content
- Notif makes you worried something went wrong

**Comment by sourishkrout** [comment]
Quick picker it is! Thanks for working thru the alternatives

**Pull request merged**
