### PR TITLE
Prompt user to select default kernel

### PR DESCRIPTION
**Pull request by mxsdev**
Should solve #497, though I don't have a repro unfortunately

TODO: tests

### CODE REVIEW

**Comment by sourishkrout** [comment]
Can't repro either, which might be a good thing 🤷 ?

However, I'm seeing a lot of these:

```ERR Cannot get cell UUID for non-code cell!```

**Comment by sourishkrout** [comment]
Ah!

image

Which also explains why the "Stop Task" button disappeared from the status bar.

**Review by sourishkrout — CHANGES_REQUESTED** [review]
Please see comments.

**Comment by mxsdev** [comment]
> ERR Cannot get cell UUID for non-code cell!

This I think is a separate issue. I pushed a fix anyway though

**Comment by mxsdev** [comment]
> Can't repro either, which might be a good thing 🤷 ?

I didn't eliminate the issue, only made it like before, where you would get prompted to select a default kernel.

I don't know where vscode stores the "default kernel" setting, but we would need to reset that to test it properly.

**Comment by sourishkrout** [comment]
Thanks for fixing the unrelated bug.

There's a chance that the kernel selection logic is something the VS Code platform improved. I remember researching it and people saying that this "select kernel first" issue couldn't be avoided in "VS Code API user-land".

**Review by sourishkrout — APPROVED** [review]
Let's merge and move on for now 👍 .

**Pull request merged**
