### PR TITLE
Fixing the mimeType description to 'output' 

### PR DESCRIPTION
**Pull request by SebasRomero**
Just changed the config typo #584

### CODE REVIEW

**Comment by admc** [comment]
Thank you for your contribution! 👍

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Thanks for your contribution!

**Comment by christian-bromann** [comment]
Hey @SebasRomero , would you mind to re-open the PR? We have to merge it on our side first to include it into the code base. I didn't merge right away as I wanted to give others time to comment.

**Comment by SebasRomero** [comment]
It doesn't let me to re open it, it's okay if I do a new PR?

**Comment by christian-bromann** [comment]
> It doesn't let me to re open it, it's okay if I do a new PR?

Totally, just open a new one.

**Pull request closed without merging**
