### PR TITLE
Non-blocking event reporting

### PR DESCRIPTION
**Pull request by sourishkrout**
Use subject (special observable) to separate the producer from the consumer to keep the producer path unblocked.

### CODE REVIEW

**Comment by sourishkrout** [comment]
@jlewi, let me know if this still works as expected. I tested it locally, and it works.

**Comment by jlewi** [comment]
Thanks. I probably won't get a chance to try it out before tuesday but feel free to merge this.

**Comment by sourishkrout** [comment]
No rush. The diff should be easy to rebase/merge.

**Comment by jlewi** [comment]
Sorry for the delay. As far as I can tell this is working as intended so merging it.

**Pull request merged**
