### PR TITLE
Add create new Runme notebook menu item

### PR DESCRIPTION
**Pull request by christian-bromann**
implements #91

create

### CODE REVIEW

**Comment by sourishkrout** [comment]
@christian-bromann does it show up in the `File -> New File` options for you? It does not for me. The idea is not to run it directly from the command palette btw.

image

**Comment by sourishkrout** [comment]
From the looks of it, the `"file/newFile"` is not in the right place in package.json and it likely needs an activation event.

**Review by sourishkrout — CHANGES_REQUESTED** [review]
Please see comments.

**Comment by christian-bromann** [comment]
@sourishkrout fixed contribution point and also added a link to the Runme docs:

newnew

**Review by sourishkrout — APPROVED** [review]
👍  with #100

**Pull request merged**
