### PR TITLE
Try stable and see if chromedriver is available now

### PR DESCRIPTION
**Pull request by sourishkrout**
Unfortunately there's always a lag after a new VS Code major release comes out.

### CODE REVIEW

**Comment by sourishkrout** [comment]
Not quite `SevereServiceError: Couldn't set up Chromedriver Response code 404 (Not Found)`.

**Comment by sourishkrout** [comment]
As per https://raw.githubusercontent.com/microsoft/vscode/1.86.0/cgmanifest.json it requires chromedriver 118.

Weirdly enough the chromedriver is not available yet: https://chromedriver.storage.googleapis.com/LATEST_RELEASE_118

**Comment by sourishkrout** [comment]
@pastuxso it appears the way Electron/Chromium is being matched with Chromedriver has changed: https://chromedriver.chromium.org/downloads/version-selection

It appears that there is no Chromedriver for version 118 specifically. The doc above says to use the previous version, so we may have to implement a retry that incrementally decreases the version number. Something we should probably "stage" locally to prove it works before implementing all the logic in the upstream project:

https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/launcher.ts#L206-L238

**Review by pastuxso — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
