### PR TITLE
Make the Gist listings on GH profile page more useful

### PR DESCRIPTION
**Pull request by sourishkrout**
Summary last, as in prefix with "summary-" which alphabetically gives it lower priority.

### CODE REVIEW

**Review by pastuxso — CHANGES_REQUESTED** [review]
I think you should consider file names starting after the s. i.e. **t, u, w, etc.**

image

**Comment by sourishkrout** [comment]
> I think you should consider file names starting after the s. i.e. **t, u, w, etc.**

I know, but I really think leaving it up to "alphabetical chance" is honest and if the summary shows up first accordingly. That's okay. We just don't want it to be unfairly prioritized, @pastuxso.

**Comment by pastuxso** [comment]
@sourishkrout Thanks for clarifying.

**Review by pastuxso — APPROVED** [review]
LGTM!

**Pull request merged**
