### PR TITLE
Add initialisation logging and test coverage

### PR DESCRIPTION
**Pull request by christian-bromann**
refs #28

As a first step to debug this issue this patch adds some logging for when initialisation for the extension fails. For that I did some minor refactoring to make code a bit more testable.

### CODE REVIEW

**Comment by sourishkrout** [comment]
@christian-bromann this branch won't run for me. looks like test fail too?

**Comment by christian-bromann** [comment]
Yeah, have to rebase. One sec.

**Comment by christian-bromann** [comment]
@sourishkrout should be ready for review now.

**Review by sourishkrout — APPROVED** [review]
LGTM 👍

**Pull request merged**
