### PR TITLE
Provide better feedback on Form validation

### PR DESCRIPTION
**Pull request by degrammer**
Small fix to provide better form validation while the user types

better-validation

### CODE REVIEW

**Comment by christian-bromann** [comment]
One suggestion: if no value is entered can it autofill it with its default value?

**Review by sourishkrout — APPROVED** [review]
👍  LGTM

**Comment by degrammer** [comment]
> One suggestion: if no value is entered can it autofill it with its default value?

@christian-bromann we could, but I'm wondering if that's a good idea, since the default value will be applied anyway? if we add that, it will end up in the annotation being added all the time to the markdown file.

**Comment by sourishkrout** [comment]
> > One suggestion: if no value is entered can it autofill it with its default value?
> 
> @christian-bromann we could, but I'm wondering if that's a good idea, since the default value will be applied anyway? if we add that, it will end up in the annotation being added all the time to the markdown file.

let's skip it this time. defaults are local to the extension. something we need to fix but don't have the time for right now.

**Pull request merged**
