### PR TITLE
Going back to the latest stable VS Code version to perform e2e tests

### PR DESCRIPTION
**Pull request by pastuxso**
It seems that the command `> Developer: Reload Window` is generating a disconnection between the test runner and the chromedriver. This step is required to test Lifecycle Identity e2e Tests using different combinations of settings.

This PR refactors the Lifecycle ID e2e tests to avoid the usage of **Window Reloading** and enabled the latest version again.

Reverts stateful/vscode-runme#1622

Related: https://github.com/webdriverio-community/wdio-vscode-service/issues/136

### CODE REVIEW

**Comment by sourishkrout** [comment]
🤔, we want to make changes to the lifecycle ID stuff soon. So I'd say let's continue to run tests against the old version of vscode and consider disabling the relevant tests in favor of running against `stable` later. That's a short-term trade-off that aligns better with our roadmap, @pastuxso.

**Review by sourishkrout — CHANGES_REQUESTED** [review]
Please see comments.

**Comment by pastuxso** [comment]
@sourishkrout Let's keep it open, I'll do a follow-up next week. For now, main is running using the v1.92.2, so no changes are necessary.

I'll convert it to draft again.

**Comment by diyer** [comment]
@pastuxso @sourishkrout , regarding this issue "It seems that the command > Developer: Reload Window is generating a disconnection between the test runner and the chromedriver. ", do you know if this will be fixed anytime soon?

**Comment by pastuxso** [comment]
> @pastuxso @sourishkrout , regarding this issue "It seems that the command > Developer: Reload Window is generating a disconnection between the test runner and the chromedriver. ", do you know if this will be fixed anytime soon?

Hi @diyer! No, we don't. For now, We are using the **1.92.2**.

**Review by sourishkrout — APPROVED** [review]
👍 LGTM

**Pull request merged**
