### PR TITLE
Annotations UI Improvements

### PR DESCRIPTION
**Pull request by degrammer**
Introducing UI tweaks for annotations, includes:
- placeholders instead of labels for textinput
- Remove grid component for composing the layout, it adapts to the screen width and behaves well under zoom in/out

TODO: Include an explanatory "?" for each element

demo-ui

dem

Solves [https://github.com/stateful/vscode-runme/issues/131](url)

Light Mode

light

Dark Mode
dark

### CODE REVIEW

**Comment by degrammer** [comment]
I would like to include some icons to the extension, @sourishkrout  can we install [codeicons](https://github.com/microsoft/vscode-codicons) for the extension?

**Comment by sourishkrout** [comment]
> I would like to include some icons to the extension, @sourishkrout can we install [codeicons](https://github.com/microsoft/vscode-codicons) for the extension?

Go for it. Don't see a reason why we can't.

**Comment by sourishkrout** [comment]
I do like the additional extra space have available now horizontally. Since you requested a reviews, is it save for me to go ahead make some edits to the textual parts @degrammer?

**Comment by degrammer** [comment]
> I do like the additional extra space have available now horizontally. Since you requested a reviews, is it save for me to go ahead make some edits to the textual parts @degrammer?

@sourishkrout  yes go ahead, merge it and I can continue working on remaining features as a separate PR

**Review by sourishkrout — APPROVED** [review]
👍 let's merge

**Pull request merged**
